FROM node:14-slim
LABEL maintainer="hello@wagtail.io"

RUN apt-get update && apt-get install rsync -y
COPY ./wagtail/package.json ./wagtail/package-lock.json ./

RUN npm --prefix / install --loglevel info
